Use ligo binary from $PATH if available
pinnacle-labs/taqueria pull request #1920
Opened 2023-10-19 08:36 UTC by callistonianembrace

# 🌮 Taqueria PR

## 🪁 Description

`ligo` binary available globally can be faster to load and run. This PR looks into $PATH and if it finds it - uses it instead of the docker image

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🐚 Required changes to the VScE have been made
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

This PR introduces a new function `baseDriverCmd` that tries to resolve a ligo binary from $PATH and uses it instead of the docker run command

## 🎢 Test Plan

_Please describe the testing strategy and plan for this PR. Keep this lightweight and anticipate any testing challenges_

## 🛸 Type of Change

- [ ] 🧽 Chore ➾
- [ ] 🛠️ Fix ➾
- [ ] ✨ Feature ➾
- [ ] 👷 Refactor ➾
- [ ] 🧪 Pre-Release ➾
- [ ] 🚀 Release ➾

2023-10-19 09:11 UTC, ulrikstrid reviewed
Initial pass looks good, I'm not sure if we should bump the version here or if it's done at release instead? It seems a bit noisy

2023-10-20 10:39 UTC, callistonianembrace commented
>  I'm not sure if we should bump the version here or if it's done at release instead? 

That's Deno tooling I believe. It ran during the pre-commit hook and I had no control. I guess it was intentionally setup.

2023-10-20 13:51 UTC, mweichert commented
Wow, thanks so much! I took a few minutes to review and it looks good thus far, but I'll need to do some testing and give a more thorough review a bit later. We'll be in touch. Thanks again!

2023-10-23 18:59 UTC, mweichert requested changes
This looks great! I did find one typo that was preventing this PR from working as intended.

The only other things missing are:
- There's a ligo.ts file which provides the handler for the `ligo` task, used to execute arbitary ligo commands. Although this isn't properly needed when the `ligo` binary is available on the system, I think its more consistent to have it use the binary too if its available.
- A test in `tests/e2e/tests/e2e/ligo-plugin-e2e-tests.spec.ts` that assures the plugin will use the binary when available. Not a blocker for PR approval but is a blocker for release.

2023-10-23 18:59 UTC, mweichert commented on taqueria-lib-ligo/common.ts
> +	for (const candidatePath in paths) {
```suggestion
for (const candidatePath of paths) {
```

Otherwise, `candidatePath` will be the index of the array.

2023-10-23 19:03 UTC, mweichert commented
> Initial pass looks good, I'm not sure if we should bump the version here or if it's done at release instead? It seems a bit noisy

In a PR, we probably shouldn't bump version #s. But that's ok. In the main branch, we use [CI in a XP-kind of way](https://www.youtube.com/watch?v=Sj0Ifupu6uA&t=76s), or at least moving closer in that direction.

2023-10-27 12:27 UTC, callistonianembrace commented
@mweichert Can you please take look again? I have addressed feedback I believe.

2023-10-27 12:27 UTC, callistonianembrace commented
I have added an e2e test too

2023-10-27 12:28 UTC, callistonianembrace commented on taqueria-lib-ligo/common.ts
> +  command: string;
I'm not sure why the formatter is inconsistent here. Made sure I ran `dprint` finishing up

2023-11-07 13:30 UTC, mweichert commented
@callistonianembrace I apologize, I've been ill as of late. I'll be sure to review your changes today. Thanks so much!

2023-11-15 17:11 UTC, merged

2023-11-17 14:15 UTC, zamrokk commented
Really super fast now :P